apiVersion: v2
name: coder-observability
description: Gain insights into your Coder deployment
type: application
version: 0.6.2
dependencies:
  - name: pyroscope
    condition: pyroscope.enabled
    repository: https://grafana.github.io/helm-charts
    version: '~v1.14.1'
  - name: grafana
    condition: grafana.enabled
    repository: https://grafana.github.io/helm-charts
    version: '~v7.3.7'
  - name: prometheus
    condition: prometheus.enabled
    repository: https://prometheus-community.github.io/helm-charts
    version: '~v25.24.1'
  - name: loki
    condition: loki.enabled
    repository: https://grafana.github.io/helm-charts
    version: '~v6.7.3'
  - name: tempo
    condition: tempo.enabled
    repository: https://grafana.github.io/helm-charts
    version: '~v1.23.0'
  - name: grafana-agent
    alias: grafana-agent
    condition: grafana-agent.enabled
    repository: https://grafana.github.io/helm-charts
    version: '~0.37.0'
maintainers:
  - name: Coder Technologies, Inc.
    url: https://github.com/coder/observability/issues
keywords:
  - observability
  - coder
  - coder.com
  - cloud development environment
  - cde
sources:
  - https://github.com/coder/observability
icon: https://helm.coder.com/coder_logo_black.png
annotations:
  artifacthub.io/category: monitoring-logging
