apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-exporter-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    global:
    target:
      name: postgres
      data_source_name: '{{ include "postgres-connector-string" . }}'
      collectors:
        - notify
    collectors:
      - collector_name: notify
        metrics:
          # Add a metric to show the current usage of the Postgres "pub/sub" mechanism
          # See https://www.postgresql.org/docs/current/functions-info.html
          - metric_name: {{ include "postgres-pubsub-queue-usage-metric-name" . }}
            type: gauge
            help: "The fraction (0–1) of the asynchronous notification queue's maximum size that is currently occupied by notifications that are waiting to be processed"
            static_labels:
              hostname: {{ .Values.global.postgres.hostname }}
              database: {{ .Values.global.postgres.database }}
            values: [ usage ]
            query: |
              SELECT pg_notification_queue_usage() AS usage;