{{- if .Values.alloy.enabled }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.alloy.alloy.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  config.alloy: |- {{- include "alloy-config" . | trim | nindent 4 }}
{{- end }}