---
kind: ConfigMap
apiVersion: v1
metadata:
  name: runbooks
  namespace: {{ .Release.Namespace }}
  annotations:
    checksum/config: {{ (.Files.Glob "runbooks/**").AsConfig | indent 2 | sha256sum }}
data:
{{ (.Files.Glob "runbooks/**").AsConfig | indent 2 }}
# TODO: add linter to ensure all alerts have runbooks