apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-exporter-config
data:
  config.yaml: |-
    global:
    target:
      name: postgres
      data_source_name: '{{ include "postgres-connector-string" . }}'
      collectors:
        - notify
    collectors:
      - collector_name: notify
        metrics:
          - metric_name: pg_pubsub_usage
            type: gauge
            help: 'TODO.'
            static_labels:
              hostname: {{ .Values.global.postgres.hostname }}
              database: {{ .Values.global.postgres.database }}
            values: [ usage ]
            query: |
              SELECT pg_notification_queue_usage() AS usage;