{{- if (index .Values "grafana-agent").enabled }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ (index .Values "grafana-agent").agent.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  config.river: |- {{- include "collector-config" . | trim | nindent 4 }}
{{- end }}
