---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.collector.agent.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  config.river: |- {{- include "collector-config" . | trim | nindent 4 }}