---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-exporter
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  serviceName: postgres-exporter
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
      labels:
        app: postgres-exporter
        app.kubernetes.io/name: "database-stats"
    spec:
      containers:
        - name: postgres-exporter
          image: {{ .Values.global.postgres.exporter.image }}
          args:
            - --collector.long_running_transactions
          ports:
            - containerPort: 9187
              name: exporter
          env:
            - name: DATA_SOURCE_NAME
              value: '{{ include "postgres-connector-string" . }}'
          {{ include "postgres-secret-mount" . | nindent 10 }}
          {{- if .Values.global.postgres.volumeMounts }}
          volumeMounts:
          {{ toYaml .Values.global.postgres.volumeMounts | nindent 12 }}
          {{- end }}
      {{- if .Values.global.postgres.volumes }}
      volumes:
      {{ toYaml .Values.global.postgres.volumes | nindent 8 }}
      {{- end }}