---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-exporter
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: sql-exporter
  serviceName: sql-exporter
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        checksum/config: {{ include (print $.Template.BasePath "/configmap-sql-exporter.yaml") . | sha256sum }}
      labels:
        app: sql-exporter
    spec:
      containers:
        - name: exporter
          image: burningalchemist/sql_exporter
          args:
            - -config.file=/cfg/config.yaml
          ports:
            - containerPort: 9399
              name: exporter
          volumeMounts:
            - mountPath: /cfg/
              name: config
      volumes:
        - name: config
          configMap:
            name: sql-exporter-config
