---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-exporter
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: sql-exporter
  serviceName: sql-exporter
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        checksum/config: {{ include (print $.Template.BasePath "/configmap-sql-exporter.yaml") . | sha256sum }}
      labels:
        app: sql-exporter
        app.kubernetes.io/name: "database-stats"
    spec:
      containers:
        - name: {{ .Values.sqlExporter.containerName }}
          image: {{ .Values.sqlExporter.image }}
          args:
            - -config.file=/cfg/config.yaml
          ports:
            - containerPort: 9399
              name: exporter
          volumeMounts:
            - mountPath: /cfg/
              name: config
          {{ include "postgres-secret-mount" . | nindent 10 }}
      volumes:
        - name: config
          configMap:
            name: sql-exporter-config
