{
 "title": "Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Coder",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"coder\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "min(pg_up)", "legendFormat": "__auto" }
   ]
  },
  { "title": "Observability Tools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{container=\"metrics-server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Write Path",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"monitoring/logs/write\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Read Path",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"monitoring/logs/read\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Backend",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"monitoring/logs/backend\", container=\"loki\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Canary",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"monitoring/logs/canary\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafana Agent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"monitoring/collector/grafana-agent\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Config",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful{job=\"monitoring/metrics/server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Config",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(loki_runtime_config_last_reload_successful)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafana Agent Config",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(agent_config_last_load_successful{job=\"monitoring/collector/grafana-agent\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Storage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    prometheus_tsdb_wal_storage_size_bytes{job=\"monitoring/metrics/server\"} +\n    prometheus_tsdb_storage_blocks_bytes{job=\"monitoring/metrics/server\"} +\n    prometheus_tsdb_symbol_table_size_bytes{job=\"monitoring/metrics/server\"}\n)\n/\nprometheus_tsdb_retention_limit_bytes{job=\"monitoring/metrics/server\"}",
     "legendFormat": "Retention limit used"
    }
   ]
  }
 ]
}